name: Update ASN list

on:
  schedule:
  - cron: "43 2 * * 5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update ASNs
        run: |
          curl -A "the-furry-hubofeverything bgp.tools - hubblethewolverine@gmail.com" -sL https://bgp.tools/tags/vpsh.txt > ${{ github.workspace }}/vpsh.txt
      - name: Commit to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -am "ASN update [$(date -u -Iminutes)]"
          git push || true